# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - build
    - deploy
    
cache:
      paths:
        - node_modules/

install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

build:
  stage: build
  script:
    - npm install
  tags:
    - dalfcs_docker_kvm

deploy-dev:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/rently-services-group13.git || true
    - git push -fq heroku HEAD:master
  only:
    - development
  tags:
    - dalfcs_docker_kvm
    
deploy-prod:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/rently-services-group13.git || true
    - git push -fq heroku HEAD:master
  only:
    - master
  tags:
    - dalfcs_docker_kvm



